dockerfile: |-
  RUN apk add --no-cache build-base yaml-dev git
  RUN gem install gem_hadar bundler

script: &script |-
  echo -e "\e[1m"
  ruby -v
  echo -e "\e[0m"
  bundle install --full-index
  bundle exec rake test

fail_fast: yes

images:
  ruby:3.4-alpine: *script
  ruby:3.3-alpine: *script
  ruby:3.2-alpine: *script
