require 'tins'

module Tins
  require 'tins/xt/attempt'
  require 'tins/xt/blank'
  require 'tins/xt/count_by'
  require 'tins/xt/deep_dup'
  require 'tins/xt/file_binary'
  require 'tins/xt/full'
  require 'tins/xt/hash_symbolize_keys_recursive'
  require 'tins/xt/hash_union'
  require 'tins/xt/irb'
  require 'tins/xt/named'
  require 'tins/xt/null'
  require 'tins/xt/p'
  require 'tins/xt/partial_application'
  require 'tins/xt/range_plus'
  require 'tins/xt/require_maybe'
  require 'tins/xt/round'
  require 'tins/xt/secure_write'
  require 'tins/xt/string'
  require 'tins/xt/subhash'
  require 'tins/xt/symbol_to_proc'
  require 'tins/xt/time_dummy'
  require 'tins/xt/uniq_by'
  require 'tins/xt/write'
  require 'tins/xt/if_predicate'
end
